spring.profiles.active=local

# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------
server.port=8091
spring.application.name=rme-backend
server.servlet.context-path=/${spring.application.name}
server.servlet.application-display-name=RME backend Service
