
# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------
server.port=8081


# ----------------------------------------
# OAUTH2 PROPERTIES
# ----------------------------------------
spring.security.oauth2.client.registration.keycloak.provider=${rme.property.keycloak-oidc.name}
spring.security.oauth2.client.provider.keycloak.issuer-uri=${auth.server.host}/realms/${rme.property.keycloak.realm.name}
spring.security.oauth2.client.provider.keycloak.authorization-uri=${spring.security.oauth2.client.provider.keycloak.issuer-uri}/protocol/openid-connect/auth
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.client-id=${rme.property.portailadmin-api-name}
spring.security.oauth2.client.registration.keycloak.client-secret=fskpcOjIxOwNhbIYQJnJEwzNKFrfgdd4
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.registration.keycloak.redirect-uri=${network.host}/${server.servlet.context-path}/login/oauth2/code/${spring.security.oauth2.client.registration.keycloak.provider}
resetPasswordUrl=/
logoutUrl=${spring.security.oauth2.client.provider.keycloak.issuer-uri}/protocol/openid-connect/logout?post_logout_redirect_uri=${network.host}${server.servlet.context-path}/&client_id=${rme.property.portailadmin-api-name}
