
# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------
server.port=8095
server.servlet.context-path=/${spring.application.name}
server.servlet.application-display-name=RME backend Service


# ----------------------------------------
# MESSAGING
# ----------------------------------------
spring.messages.basename=classpath:i18n/messages


# ----------------------------------------
# API DOCUMENTATION
# ----------------------------------------
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui-custom.html
springdoc.swagger-ui.operationsSorter=method
