
# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------
server.port=8092


# ----------------------------------------
# OAUTH2 PROPERTIES
# ----------------------------------------
spring.security.oauth2.resourceserver.jwt.issuer-uri=${auth.server.host}/realms/${rme.property.keycloak.realm.name}
