# ----------------------------------------
## DATASOURCE PROPERTIES
# ----------------------------------------
spring.datasource.url=jdbc:oracle:thin:@oradev.bnquebec.ca:1521/banqdev
spring.datasource.username=RME_APP
spring.datasource.password=rme_app


# ----------------------------------------
# JPA PROPERTIES
# ----------------------------------------
spring.datasource.driver.class=oracle.jdbc.driver.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.datasource.hikari.connection-init-sql=ALTER SESSION SET NLS_COMP='LINGUISTIC' NLS_SORT='FRENCH_AI'
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.id.optimizer.pooled.preferred=pooled-lo
spring.jpa.properties.hibernate.id.db_structure_naming_strategy=legacy
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.open-in-view=false



# ----------------------------------------
# HOSTS PROPERTIES
# ----------------------------------------
network.host=http://localhost:${server.port}
rabbitmq.server.host=
auth.server.host=
koha.server.host=
files.rme.api.host=
batch.rme.api.host=
koha.rme.api.host=
portailadmin.rme.api.host=
portailweb.rme.api.host=
#resource.server.url=${auth.server.host}
