
# ----------------------------------------
# HOSTS PROPERTIES
# ----------------------------------------
network.host=http://localhost:${server.port}
rabbitmq.server.host=
auth.server.host=
koha.server.host=
files.rme.api.host=
batch.rme.api.host=
koha.rme.api.host=
portailadmin.rme.api.host=
portailweb.rme.api.host=
#resource.server.url=${auth.server.host}
